Repository cognitedata/opcua-extractor-net, pull requests merged in 2023-11, with the labels that each got.

#512 Respect TypesToMap
  Extractor/Config/CogniteConfig.cs
  Extractor/Pushers/FDM/FDMWriter.cs
  Extractor/Pushers/FDM/InstanceBuilder.cs
  Extractor/Pushers/FDM/NodeTypeCollector.cs
  Extractor/Pushers/FDM/TypeHierarchyBuilder.cs
  Extractor/Pushers/FDM/Types/NodeTypes.cs
  Test/Unit/FDMTests.cs
Labels: auto-merge

#523 Remove proto nodeId fallback
  ConfigurationTool/Checks/DataTypes.cs
  ConfigurationTool/UAServerExplorer.cs
  Extractor/Config/EventConfig.cs
  Extractor/Config/ExtractionConfig.cs
  Extractor/SessionContext.cs
  Extractor/UAExtractor.cs
Labels: auto-merge, auto-update

#528 Increase slack and add option to disable sub recreation
  Extractor/Config/SubscriptionConfig.cs
  Extractor/Subscriptions/RecreateSubscriptionTask.cs
  Extractor/Subscriptions/SubscriptionManager.cs
  config/config.example.yml
  schema/subscription_config.schema.json
Labels: auto-merge, auto-update

#525 New server failure framework
  Extractor/Config/SourceConfig.cs
  Extractor/Subscriptions/BaseCreateSubscriptionTask.cs
  Server/DebugMasterNodeManager.cs
  Server/ErrorCallbacks.cs
  Server/IServerRequestCallbacks.cs
  Server/Program.cs
  Server/TestServer.cs
  Test/Unit/ConfigToolTest.cs
  Test/Unit/UAClientTest.cs
Labels: auto-merge, auto-update

#526 Clear delete marker on clean resources
  Extractor/Pushers/PusherUtils.cs
  Extractor/Pushers/Writers/CleanWriter.cs
Labels: auto-merge, auto-update

#510 Track namespacepublicationdate - dog-2234
  Extractor/Config/StateStorageConfig.cs
  Extractor/Looper.cs
  Extractor/RebrowseTriggerManager.cs
  Extractor/Subscriptions/RebrowseTriggerSubscriptionTask.cs
  Extractor/UAExtractor.cs
  Server/NodeManager.cs
  Server/TestServer.cs
  Test/Integration/RebrowseTriggerManagerTests.cs
Labels: auto-update

#533 Properly reset max node parallelism if it changes
  Extractor/Browse/Browser.cs
  Extractor/Extractor.csproj
  Extractor/History/HistoryReader.cs
  Extractor/UAExtractor.cs
  Test/Test.csproj
  schema/cognite_config.schema.json
  schema/full_config.schema.json
  schema/logger_config.schema.json
  schema/metrics_config.schema.json
  schema/state_storage_config.schema.json
  schema/ua_retries_config.schema.json
Labels: auto-merge

#543 Bump version
  manifest.yml
Labels: auto-merge
